

- name: Clone the Odoo repository via HTTPS
  hosts: all
  become: no        # Default
  vars:
    repo_url: "https://github.com/odoo/odoo.git"
    dest_dir: "/opt/odoo"

  tasks:
    - name: Ensure git installed
      ansible.builtin.package:
        name: git
        state: present
      become: yes

    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure "{{ dest_dir }}" is owned by user ec2-user and group ec2-user
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        owner: ec2-user
        group: ec2-user
        mode: '0755' 
        recurse: yes
      become: yes

    - name: Clone the Odoo repository (HTTPS)
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        accept_hostkey: yes
        clone: yes
        update: no
      become: no


