- name: Set custom prompt (PS1) for users
  ansible.builtin.copy:
    content: "{{ lookup('template', 'prompt.sh.j2') }}"
    dest: /etc/profile.d/custom_ps1.sh
    owner: root
    group: root
    mode: '0644'
