# - name: Ensure curl is installed
  # ansible.builtin.package:
    # name: curl
    # state: present

---

- name: Create SSH keypair for user alice
  hosts: all
  become: yes
  vars:
    ssh_user: ec2-user
    ssh_dir: "/home/{{ ssh_user }}/.ssh"
    key_name: "id_rsa"


- hosts: all
  gather_facts: false
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Generate SSH keypair for user
      community.crypto.openssh_keypair:
        path: "/home/{{ ansible_user }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      become: true
      become_user: "{{ ansible_user }}"

