- hosts: all
  become: yes
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- hosts: all
  become: yes
  roles:
    - prompt

# - hosts: odoo-17
  # become: yes
  # tasks:
    # - name: Install Odoo software (17)
      # ansible.builtin.git:
      # repo: "https://github.com/odoo/odoo.git"
      # dest: "/opt/odoo"
      # version: "17.0"    # <-- The branch you want
      # force: no                   # Optional: force checkout if dest exists
      # update: no                  # Optional: pull latest changes if repo exists
   
